from enum import Enum


class ErrorCode(str, Enum):
    CONFIG_MISSING = "CONFIG_MISSING"
    CONFIG_INVALID = "CONFIG_INVALID"

    LLM_API_ERROR = "LLM_API_ERROR"
    LLM_STREAM_ERROR = "LLM_STREAM_ERROR"

    TRANSLATE_API_ERROR = "TRANSLATE_API_ERROR"
    TRANSLATE_EMPTY_RESULT = "TRANSLATE_EMPTY_RESULT"

    TTS_CONNECTION_ERROR = "TTS_CONNECTION_ERROR"
    TTS_API_ERROR = "TTS_API_ERROR"
    TTS_STREAM_ERROR = "TTS_STREAM_ERROR"

    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    PIPELINE_ERROR = "PIPELINE_ERROR"
    WEBSOCKET_ERROR = "WEBSOCKET_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
